/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: nigelgoh (https://sketchfab.com/nigelgoh)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/viking-room-a49f1b8e4f5c4ecf9e1fe7d81915ad38
title: Viking room
*/

// import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Room(props) {
  const group = useRef()
  // const { nodes } = useLoader(GLTFLoader, './modelos/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh visible userData={{ test: "hello" }} position={[0, 0, 0]} rotation={[0, 0, 0]}>
                    <sphereGeometry attach="geometry" args={[4,4, 4]} />
                    <meshStandardMaterial attach="material" wireframe />
        </mesh>
        <mesh visible userData={{ test: "hello" }} position={[10, 10, 10]} rotation={[0, 0, 0]}>
                    <sphereGeometry attach="geometry" args={[4,4, 4]} />
                    <meshStandardMaterial attach="material"  />
        </mesh>
          
        </group>
      </group>
    </group>
  )
}
